---
- hosts: all
  become: yes
  tasks:
   - name: install apache
     apt: 
       name: apache2
       state: present

   - name: install tree
     apt: 
       name: tree
       state: present

   - name: install git
     apt: 
       name: git
       state: present    
