---
- name: creat tomcat group
  group:
    name: tomcat
    state: present

- name: creat tomcat user
  user:
    name: tomcat
    shell: /bin/false
    groups: tomcat
    state: present
    append: yes

